FROM node:22-slim

# Environment variables
ENV DEBIAN_FRONTEND=noninteractive

ARG BACKEND_PORT
ENV BACKEND_PORT=$BACKEND_PORT

# Install some basic tools
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    ca-certificates \
    curl \
    git \
    unzip \
    zip \
    nano \
    wget && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Set the working directory
COPY . /server
WORKDIR /server

# Give the entrypoint.sh file the right permissions
RUN chmod +x /server/entrypoint.sh

# Install Bun
RUN curl -fsSL https://bun.sh/install | bash

# Add bun to PATH
ENV BUN_INSTALL="/root/.bun"
ENV PATH="$BUN_INSTALL/bin:$PATH"

# Expose the port
EXPOSE ${BACKEND_PORT}

# Install npm-packages & run the app
ENTRYPOINT ["/server/entrypoint.sh"]